# .github/workflows/unzip_and_push.yml

name: Unzip and Push Build Artifact

# 仅支持手动触发
on:
  workflow_dispatch:  # 允许通过 GitHub Actions 页面手动触发

jobs:
  unzip_commit_push:
    runs-on: ubuntu-latest # 使用最新的 Ubuntu 运行环境

    # 为作业步骤授予写入仓库内容的权限，以便推送更改
    permissions:
      contents: write

    steps:
      # 第一步：检出代码
      # 拉取你的仓库代码到 Actions 运行器中
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # 确保我们获取了完整的历史记录，以便正确推送
          fetch-depth: 0
          # 使用 GITHUB_TOKEN 进行身份验证，以便后续推送
          token: ${{ secrets.GITHUB_TOKEN }}

      # 第二步：解压 zip 文件
      # 查找并解压 main 分支根目录下的 imemscan_ipa_build.zip
      # -o 选项表示覆盖现有文件而不询问
      - name: Unzip build artifact
        run: |
          if [ -f imemscan_ipa_build.zip ]; then
            echo "Found imemscan_ipa_build.zip. Unzipping..."
            unzip -o imemscan_ipa_build.zip
            echo "Unzip completed."
          else
            echo "Error: imemscan_ipa_build.zip not found in the root directory."
            # 你可以选择在这里失败 Action
            # exit 1
            # 或者只是记录信息然后继续（注意：后续步骤可能因为没有新文件而无效）
          fi

      # 第三步：显示当前路径
      - name: Show current path
        run: pwd

      # 第四步：列出解压后的内容
      # 显示当前目录下所有文件和文件夹的详细列表
      - name: List extracted files
        run: ls -la

      # 第五步：配置 Git 用户信息
      # 设置用于提交的用户名和邮箱
      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      # 第六步：添加、提交并推送更改（排除 .github/workflows 目录）
      - name: Add, commit, and push changes
        run: |
          # 添加除 .github/workflows 目录外的所有更改
          git add .
          git reset -- .github/workflows/
          
          # 检查是否有实际更改需要提交
          if git diff --staged --quiet; then
            echo "No changes to commit (excluding .github/workflows)."
          else
            echo "Changes detected (excluding .github/workflows). Committing..."
            # 提交更改，commit message 中包含 [skip ci] 以防止触发自身
            git commit -m "Add unzipped content from imemscan_ipa_build.zip (exclude workflows) [skip ci]"

            echo "Pushing changes to main branch..."
            # 使用完整的引用规范推送到远程仓库的 main 分支
            git push origin HEAD:main
          fi
        # 可选：如果解压后不再需要 zip 文件，可以在这里删除它
        # run: rm -f imemscan_ipa_build.zip

